NTier.UI/Areas/Admin/Controllers/AppUserController.cs
using NTier.Model.Entities;
using NTier.Service.Option;
using NTier.UI.Helpers;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTier.UI.Areas.Admin.Controllers
{
    //[CustomAuthorize(Role.Admin)]
    public class AppUserController : Controller
    {
        AppUserService _appUserService;
        public AppUserController()
        {
            _appUserService = new AppUserService();
        }

        public ActionResult List(int page = 1)
        {
            List<AppUser> model = _appUserService.GetActives();
            return View(model.ToPagedList(page, 10));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AppUser data, HttpPostedFileBase image)
        {
            data.ImagePath = ImageUploader.UploadSingleImage("~/Uploads/", image);

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
                data.ImagePath = "~/Uploads/48718ae0-cc55-4377-94ce-de4b69cbf590.jpg";

            _appUserService.Add(data);
            return Redirect("~/Admin/AppUser/List");
        }

        public ActionResult Edit(Guid id)
        {
            AppUser appUser = _appUserService.GetById(id);
            return View(appUser);
        }

        [HttpPost]
        public ActionResult Edit(AppUser data, HttpPostedFileBase image)
        {
            //Elimizdeki imajı güncelleme esnasında kaybetmemek içinbir kontrol daha uyguluyoruz.
            AppUser updated = _appUserService.GetById(data.Id);

            if (image != null) data.ImagePath = ImageUploader.UploadSingleImage("~/Uploads/", image);
            else
                data.ImagePath = updated.ImagePath;

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
            {                
                if (updated.ImagePath == null || updated.ImagePath == "~/Uploads/48718ae0-cc55-4377-94ce-de4b69cbf590.jpg")
                    data.ImagePath = "~/Uploads/48718ae0-cc55-4377-94ce-de4b69cbf590.jpg";
                else data.ImagePath = updated.ImagePath;                
            }
            _appUserService.Update(data);
            return Redirect("~/Admin/AppUser/List");
        }

        public ActionResult Details(Guid id)
        {
            return View(_appUserService.GetById(id));
        }

        public RedirectResult Delete(Guid id)
        {
            _appUserService.Remove(id);
            return Redirect("~/Admin/AppUser/List");
        }
    }
}

NTier.UI/Areas/Admin/Views/AppUser/Create.cshtml
@model NTier.Model.Entities.AppUser

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_SharedAdminLayout.cshtml";
}

<div class="row ">
    <div class="col-md-2"></div>
    <div class="col-md-8 " style="margin-top:5%">
        <form action="/Admin/AppUser/Create" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="Name">İsmi</label>
                <input type="text" name="Name" value="" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Surname">Soyismi</label>
                <input type="text" name="Surname" value="" class="form-control" />
            </div>
            <div class="form-group">
                <label for="PhoneNumber">Telefon</label>
                <input type="text" name="PhoneNumber" value="" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Address">Adres</label>
                <input type="text" name="Address" value="" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Email">E-Mail</label>
                <input type="text" name="Email" value="" class="form-control" />
            </div>
            <div class="form-group">
                <label for="UserName">Kullanıcı Adı</label>
                <input type="text" name="UserName" value="" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Password">Şifre</label>
                <input type="password" name="Password" value="" class="form-control" />
            </div>
            <div class="form-group">
                <label for="ImagePath">Fotoğraf</label>
                <input type="file" name="image" value="" />
            </div>
            <div class="form-group">
                <label for="Role">Rol</label>
                <select name="Role">
                    @foreach (var item in Enum.GetNames(typeof(NTier.Model.Entities.Role)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
            </div>
            <input type="submit" value="Ekle" class="form-control btn btn-primary" />
        </form>


        <div>
            @Html.ActionLink("Back to List", "List")
        </div>

    </div>
    <div class="col-md-2"></div>
</div>

NTier.UI/Areas/Admin/Views/AppUser/Details.cshtml
@model NTier.Model.Entities.AppUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_SharedAdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AppUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            <img src="@Model.ImagePath" style="display:block;" width="100" height="100"/>
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MasterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MasterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedComputerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedComputerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedIp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedIp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAtUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAtUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedComputerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedComputerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedIp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedIp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedAtUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedAtUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NTier.UI/Areas/Admin/Views/AppUser/Edit.cshtml
@model NTier.Model.Entities.AppUser
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_SharedAdminLayout.cshtml";
}

<div class="row ">
    <div class="col-md-2"></div>
    <div class="col-md-8 " style="margin-top:5%">
        <form action="/Admin/AppUser/Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" name="Id" value="@Model.Id" />
            <div class="form-group">
                <label for="Name">İsmi</label>
                <input type="text" name="Name" value="@Model.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Surname">Soyismi</label>
                <input type="text" name="Surname" value="@Model.Surname" class="form-control" />
            </div>
            <div class="form-group">
                <label for="PhoneNumber">Telefon</label>
                <input type="text" name="PhoneNumber" value="@Model.PhoneNumber" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Address">Adres</label>
                <input type="text" name="Address" value="@Model.Address" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Email">E-Mail</label>
                <input type="text" name="Email" value="@Model.Email" class="form-control" />
            </div>
            <div class="form-group">
                <label for="UserName">Kullanıcı Adı</label>
                <input type="text" name="UserName" value="@Model.UserName" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Password">Şifre</label>
                <input type="password" name="Password" value="@Model.Password" class="form-control" />
            </div>
            <div class="form-group">
                <label for="ImagePath">Kullanıcı Resmi</label>
                <img src="@Model.ImagePath" style="display:block;" width="100" height="100" />
            </div>
            <div class="form-group">
                <label for="ImagePath">Fotoğraf</label>
                <input type="file" name="image" value="" />
            </div>
            <div class="form-group">
                <label for="Role">Rol</label>
                <select name="Role">
                    @foreach (var item in Enum.GetNames(typeof(NTier.Model.Entities.Role)))
                    {
                        if (item == Model.Role.ToString())
                        {
                            <option selected value="@item">@item</option>
                        }
                        else
                        {
                            <option value="@item">@item</option>
                        }
                    }
                </select>
            </div>
            <input type="submit" value="Ekle" class="form-control btn btn-primary" />
        </form>


        <div>
            @Html.ActionLink("Back to List", "List")
        </div>

    </div>
    <div class="col-md-2"></div>
</div>

NTier.UI/Areas/Admin/Views/AppUser/List.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<NTier.Model.Entities.AppUser>

@{
    ViewBag.Title = "List";
    Layout = "~/Areas/Admin/Views/Shared/_SharedAdminLayout.cshtml";
}
<div class="col-md-12">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Kullanıcı İsmi</th>
                <th>Kullanıcı Soyismi</th>
                <th>Username</th>
                @*<th>Password</th>*@
                <th>Telefon Numarası</th>
                <th>Adres</th>
                <th>Email</th>
                <th>Rol</th>
                <th>Fotoğraf</th>
                <th colspan="3">Güncelle / Detay / Sil</th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @item.Name
        </td>
        <td>
            @item.Surname
        </td>
        <td>
            @item.UserName
        </td>
        @*<td>
            @item.Password
        </td>*@
        <td>
            @item.PhoneNumber
        </td>
        <td>
            @item.Address
        </td>
        <td>
            @item.Email
        </td>
        <td>
            @item.Role
        </td>
       <td>
           <img src="@item.ImagePath" style="display:block;"width="30" height="30" />
       </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
        }

    </table>
    <div class="pagedList">
        @Html.PagedListPager(Model, page => Url.Action("List", "AppUser", new {page}), PagedListRenderOptions.Classic)
    </div>
</div>